### ISSUE TITLE
Auto-insertion of threat description broken

### ISSUE THREAD

**Issue by matthewejones** [dehydr8/elevation-of-privilege#131]
When you created a threat when playing elevation of privilege it automatically took the description off the card as the default description for the threat. It might be nice to also implement this for cornucopia.

This is defined in `src/game/definitions.js`

**Comment by ChristophNiehoff** [comment]
Actually, it is more than that:  The strings in `src/game/definitions.js` are still indexed using the old (STRIDE-based) card names. As a result, auto-insertion of the threat description is even broken for EoP right now...

**Comment by ChristophNiehoff** [comment]
But for Cornucopia I am not so sure, if this helps so much. The descriptions on the cards are rather lengthy and always start with some hacker name that you don't want to write down in an serious report.
