### ISSUE TITLE
Some cards are not visible

### ISSUE THREAD

**Issue by ChristophNiehoff** [dehydr8/elevation-of-privilege#140]
On current master, the deck contains the card `E2` bu this is not visible. Maybe it's got something to do with `B2` being in `STARTING_CARD_MAP` and `INVALID_CARDS` at the same time? Should `INVALID_CARDS` rather contain `E2`?

Are `STARTIND_CARD_MAP` and `INVALID_CARDS` correct for all suits?

![Screenshot from 2021-08-13 11-55-09](https://user-images.githubusercontent.com/10673021/129341822-a6200ab0-74d8-471a-82df-53bc98594225.png)

**Comment by matthewejones** [comment]
I think there's just been a bit of confusion when changing the letters over. The two of tampering (E2) doesn't actually exist which is why it's invisible and should be invalid. B2 which is the two of information disclosure should be allowed. I'll resolve this in #138
