### ISSUE TITLE
Heroku deployment fails

### ISSUE THREAD

**Issue by ChristophNiehoff** [dehydr8/elevation-of-privilege#68]
After switching the base image for the heroku docker container to alpine, the heroku deployment fails (see https://travis-ci.org/github/dehydr8/elevation-of-privilege/jobs/773068262)

It seems that building the container already fails when pulling the alpine image from the registry
```
$ docker build -f heroku/Dockerfile -t $REPO:$COMMIT .
Sending build context to Docker daemon  17.97MB
Step 1/14 : FROM alpine:3
3: Pulling from library/alpine
540db60ca938: Pulling fs layer
error pulling image configuration: unexpected EOF
The command "docker build -f heroku/Dockerfile -t $REPO:$COMMIT ." exited with 1.
```

Locally, the docker command runs just fine for me. @dehydr8 Do you have any idea?

**Comment by dehydr8** [comment]
I'll take a look at this today.

**Comment by dehydr8** [comment]
I ran the job again and it worked. Not sure why it failed to fetch the image from registry when it ran previously.

**Comment by ChristophNiehoff** [comment]
Hooray! 🎉 Also today's deployment worked.
