### ISSUE TITLE
Player secrets are not validated

### ISSUE THREAD

**Issue by ChristophNiehoff** [dehydr8/elevation-of-privilege#70]
The secrets in the route `"/:game/:id/:secret"` are not validated when a user enters the game. This is unfortunate, since one player can easily impersonate another player.

This also affects downloading the model json.

Maybe this is fixed by #69 ?

**Comment by matthewejones** [comment]
Looks like the updated version fixes this, the page just shows "connecting..." if the secret is invalid.

You're probably right though that the download files should be protecting with a secret

**Comment by ChristophNiehoff** [comment]
@matthewejones I can confirm that the secrets get validated with the newer boardgame.io version! :tada: 
But I am not sure what happens if the user enters a wrong `gameId`. In this case it seems that an instance of the game is returned but the game state seems to be empty?  Could you have a look at it, please?

**Comment by matthewejones** [comment]
yep, I'll look into it and maybe add some kind of validation to check the gameId exists
